### ISSUE TITLE
`CodatLink.tsx` files are inconsistent between examples and docs

### ISSUE THREAD

**Issue by LucasLemanowicz** [codatio/sdk-link#19]
The `CodatLink.tsx` files are inconsistent between each other among the examples, and also between the docs.

As an example:
* The docs discuss having a `nonModal` option here: https://docs.codat.io/auth-flow/authorize-embedded-link#non-modal-styling
* When I follow the NextJS installation guide, the docs themselves link to a missing file: https://docs.codat.io/auth-flow/authorize-embedded-link#get-started
* When I find the right file, the `CodatLink.tsx` doesn't have an option prop:  https://github.com/codatio/sdk-link/blob/main/examples/languages/next/src/app/components/CodatLink.tsx
* I then need to find an example that has an `options` prop and copy over the right types and changes manually: https://github.com/codatio/sdk-link/tree/main/examples/non-modal

Since you are not providing an npm library, can you please at least make sure the files in the repo are consistent, and the docs link to the right places?

**Comment by dcoplowe** [comment]
Hi Lucas,

I'm sorry to hear that you've not had a great experience with out docs. I'll make sure to yet these inconsistencies corrected. 

Please let me know if you need any further assistance or if you managed to embed Link into your application.

Many thanks,

David
